### ISSUE TITLE
Make a spot show for x days in the future

### ISSUE THREAD

**Issue by JozoSalt** [hyperoslo/spot-hyper#10]
If you are going to have the same spot for a period of time, you could just set `/spotme working on stuff --due_date 01-01-3018`
This would make the same spot show for that user until 01-01-3018

**Comment by gauravtiwari** [comment]
Hey @JozoSalt (Sigvart) - I think this can be great enhancement, but slack commands has some limitations, unfortunately we can only pass one `text` argument with the slack command. We can do some work around like parsing the text and figuring out if due date is present in that text, but not sure if it's a good solution. What do you think?
