### ISSUE TITLE
Hashtags are moved to the end

### ISSUE THREAD

**Issue by sindrenm** [hyperoslo/spot-hyper#2]
I noticed the hashtags are moved to the end of the post. This might totally be a feature, but it comes with some weird side effects. I just posted the following message:

> Doing #android stuff for Norges Bank at the #office

However, it got morphed into this one, which kinda means something else:

> Doing stuff for Norges Bank at the #android #office

Is this something we should care about?

**Comment by mathiasbno** [comment]
Maybe we should only move the hashtags that have a filter. On another hand, are you working on `#android`?

**Comment by gauravtiwari** [comment]
hi @sindrenm I see, initially it was built to support your initial message, but later I played around with it to make it filterable, however I see your point and it definitely looks weird.  I will remove the separate tags display and keep the tags used within the text. This way we can get both features - filter + text is printed exactly the way you have posted. Ok ?

**Comment by sindrenm** [comment]
Sounds awesome, @gauravtiwari! :smiley: 

And yeah, @mathiasbno, I am totally working on **#android**. :+1:

**Comment by gauravtiwari** [comment]
@sindrenm :smiley:

**Comment by sindrenm** [comment]
:grinning:
